### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/keepass-dmenu#1]
The total runtime when running it on my own password database is primarily made out of (>95%) loading the database itself. There's not much that can be done to avoid this, as the only way to do it, is to store the database in clear text, either in memory or in a temporary file. Storing it in memory makes the implementation a lot less straight forward, so until it proves necessary I will not consider that.

Currently, it takes around 225 ms to load my own database, using the native Node.js implementation from keepass.io. With 

Using the C++ version distributed with keepass.io (only installed if libcrypto++-dev is installed on the system[0]) loading the database takes about half the time; around 110 ms.

On my test database the node.js implementation takes ~80ms and the native one ~20ms. 

All in all the performance is good enough using the node.js implementation that is it not a problem or even noticeable at the moment when I'm using it. And by installing the native version you will get something around a 2x speedup.

My conclusion is that it's fast enough for now at least.

0: Installed with: `sudo apt-get install libcrypto++-dev`

**Comment by gustavnikolaj** [comment]
@sunesimonsen the above investigation was prompted by your concerns about performance. I'll close this issue as I'm pretty satisfied with the performance.

The bottleneck is not in node, as the actual time spent there is neglectable compared to the actual crypto work, which can be significantly speed up by installing the native version.

Looking forwardto show you what I've got so far tomorrow at work.

**Comment by sunesimonsen** [comment]
Sound exciting :-)
