### ISSUE TITLE
[Bug] Does not accept abitrary passwords

### ISSUE THREAD

**Issue by GRBurst** [gustavnikolaj/keepass-dmenu#10]
If using a password consisting only of numbers (used by a testdb), one cannot invoke it using the `--password` argument

**Comment by gustavnikolaj** [comment]
I think this might be caused by how the yargs-module interpret the command line options. If you quote the password I'm pretty sure it will work.

**Comment by gustavnikolaj** [comment]
Released as 1.2.2 on npm.

**Comment by GRBurst** [comment]
In fact I even tried to quote it but it did not work ;-)
Now it is working, thanks!

**Comment by gustavnikolaj** [comment]
Good :-)
