### ISSUE TITLE
[Feature] Ability to use keyfiles

### ISSUE THREAD

**Issue by GRBurst** [gustavnikolaj/keepass-dmenu#11]
Currently, I can not find an option to use this tool with a keyfile. It would be nice, if one could specify an optional keyfile to unlock the database, since I am using a both, a password and a keyfile.
I suggest a `--keyfile` argument.

**Comment by gustavnikolaj** [comment]
Released with version 1.3.0 on npm. I don't use the keyfile option myself, but I verified that it was working with a newly generated db that I checked in as well.

**Comment by GRBurst** [comment]
Yes, seems to work now. Thanks a lot.

**Comment by gustavnikolaj** [comment]
You're welcome :-)
