### ISSUE TITLE
[Bug] Database can not be parsed

### ISSUE THREAD

**Issue by GRBurst** [gustavnikolaj/keepass-dmenu#12]
Hey, first things first: Thanks for your quick support!

Sadly I am running into another issue, because somehow my real database can not be parsed. In specific I am receiving the following error:
```
Load Database File: Time elapsed: 1633 ms
/usr/lib/node_modules/keepass-dmenu/lib/parseRawDatabase.js:24
        node.String.forEach(function (item) {
                    ^
TypeError: undefined is not a function
    at databaseWalker (/usr/lib/node_modules/keepass-dmenu/lib/parseRawDatabase.js:24:21)
    at Array.map (native)
    at databaseWalker (/usr/lib/node_modules/keepass-dmenu/lib/parseRawDatabase.js:14:32)
    at Array.map (native)
    at databaseWalker (/usr/lib/node_modules/keepass-dmenu/lib/parseRawDatabase.js:20:31)
    at parseRawDatabase (/usr/lib/node_modules/keepass-dmenu/lib/parseRawDatabase.js:39:12)
    at /usr/lib/node_modules/keepass-dmenu/lib/loadDatabase.js:19:49
    at /usr/lib/node_modules/keepass-dmenu/node_modules/passerror/lib/passError.js:23:33
    at Instance.<anonymous> (/usr/lib/node_modules/keepass-dmenu/node_modules/keepass.io/lib/Database.js:40:12)
    at /usr/lib/node_modules/keepass-dmenu/node_modules/keepass.io/node_modules/dejavu/node_modules/mout/function/bind.js:13:23
```

Do you have any idea what causes this error?

**Comment by gustavnikolaj** [comment]
It looks like I expect an array and that I actually find something else in your database. Normally I expect to find an array of "String" objects - but it seems that I might only get a single "String" object instead of the list of them...

I released a new version on npm (v1.3.1) which has a little addition which would support an instance of a "String" object as well... I could add it without changing the current behavior,.

**Comment by gustavnikolaj** [comment]
Try updating to v1.3.1 and let me know what happens :-)

**Comment by GRBurst** [comment]
Okay intresting. Maybe it is not directly related to a bug. You are using the title field in order to choose an entry. But there are few entries that do not have a title in my Database causing an error.

**Comment by gustavnikolaj** [comment]
Ah, yes. That's true.

What is your use-case for non-titled entries? I thought that there was none :-)

**Comment by GRBurst** [comment]
Yes some time ago I imported all my Firefox Passwords to Keepass. These entries do not have a title, only an url - since firefox matches them by the url and you do not need titles there.

**Comment by GRBurst** [comment]
I was too lazy to give them all of them a title afterwards ^^
For those entries it would be possible to choose them by url.

**Comment by gustavnikolaj** [comment]
I could use the uuid field instead, but it might be better to just filter out the non-titled entries, as you would not be able to select those from the dmenu any way...

I'll be happy to do it, if it's not too much work. I'm working on a potential replacement for keepass-dmenu, which is going to be an electron app. It's nearing completion, but I still have a few days worth of polishing before I'd recommend using it. You can find it at https://github.com/gustavnikolaj/keepass-menubar

Essentially, it will be the exact same thing as this, but it will support environments where dmenu doesn't work - e.g. OSX and Windows. The reason why I'm abandoning the dmenu based solution is that I'm able to use the process as a daemon, for storing the password, such that I don't need to serialize the deriviated key to disc to save you from inputting the same password over and over again, when you use it multiple times over a short time span.

I'd rather spend my energy there, so if it's not too much work, could you just add the urls as the titles? :-) If it's too many to be worthwhile, I'll see what I can do.

**Comment by gustavnikolaj** [comment]
Actually, I cannot use the uuid fields. dmenu would only return the string that you actually selected - so I would have to let the url field double as the title field... :-(

**Comment by GRBurst** [comment]
Yeah sure no problem :+1: 
Interesting project - so this new keepass-menubar works on his own without using dmenu?

**Comment by GRBurst** [comment]
Ah okay, had to google for electron to understand you ^^

**Comment by GRBurst** [comment]
FYK: Since I am lazy I stored my password in a gnome-keyring and using it to run keepass-dmenu with
```
keepass-dmenu --database ~/.keepass/Test.kdbx --password $(secret-tool lookup type password domain test) --keyfile ~/.keepass/Test.key
```

**Comment by gustavnikolaj** [comment]
It's an application framework for native-ish webapps - like the Atom editor from GitHub :-) It could theoretically host a dmenu frontend too instead of a browser based one, if you prefer that. I'll make sure to make some proper documentation and some demos of it, once I get the last things done.

Just to make sure, you solved the problem by adding titles to the entries right?

**Comment by GRBurst** [comment]
Yes - thanks a lot!

**Comment by gustavnikolaj** [comment]
Np! I'll close this for now :-)
