### ISSUE TITLE
use of keyfile?

### ISSUE THREAD

**Issue by andykais** [gustavnikolaj/keepass-dmenu#16]
I see in [this commit](https://github.com/gustavnikolaj/keepass-dmenu/commit/81ae49384fce903915e6ff754343337a34cb69d5) that there is a keyfile option, however, running
```bash
keepass-dmenu --keyfile Dropbox/keyfile --database Dropbox/database.kdbx --password password
```
returns 
```
name: 'KpioDatabaseError',
  message: 'Could not decrypt database. Either the credentials were invalid or the database is corrupt.' 

```

is the use of a keyfile possible at this time?

**Comment by gustavnikolaj** [comment]
I haven't used a keyfile myself, so it's entirely possible that it has regressed since, or never worked properly. I will take a look at it as soon as time permits :-)
