### ISSUE TITLE
Thanks for doing this project

### ISSUE THREAD

**Issue by kwstannard** [gustavnikolaj/keepass-dmenu#18]
It made my life a little easier.

**Comment by gustavnikolaj** [comment]
Thank you! It's nice to know that it has been useful for someone else than me. 🎆 

I'll be happy to merge any changes you might have (e.g. that thing on the open PR) if you are still using it - or even hand over ownership of the repo.

I feel a bit bad for neglecting this project if there's anyone using it, but I don't even have a system to test this on. :-(

**Comment by kwstannard** [comment]
I am also not really using it right now either because my current employer doesn't support linux and I haven't used my home computer in months. If the situation changes, this seems low key enough that I can probably take over.

**Comment by gustavnikolaj** [comment]
Let me know if it becomes relevant :-) And I'll of course be happy to help out if you hit any problems.
