### ISSUE TITLE
Caching wrong passwords

### ISSUE THREAD

**Issue by gustavnikolaj** [gustavnikolaj/keepass-dmenu#7]
The password cache file should not be written before the database has loaded. Currently, your password will be cached when it's wrong, and requiring you to delete the tmp file yourself.

**Comment by gustavnikolaj** [comment]
Fixed in 288c951bd133c3f0e62ff305697bd7b73439d7ff and released with v1.1.0.

@sunesimonsen

**Comment by sunesimonsen** [comment]
Awesome thanks.
