### ISSUE TITLE
does not accept special characters in password

### ISSUE THREAD

**Issue by fdietze** [gustavnikolaj/keepass-dmenu#8]
- for example german umlauts: äöü

**Comment by gustavnikolaj** [comment]
I'm using child_process.exec to launch dmenu. https://github.com/gustavnikolaj/keepass-dmenu/blob/master/lib/passwordPrompt.js

I don't pass any options, but the encoding option defaults to UTF-8. https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

I just tried locally, using node v0.10.31 and dmenu v4.5 on ubuntu 14.10, with both the danish æ, ø and å, but also ü (which requires me to hit two keys to construct the character on the danish keyboard). Everything works as expected.

What versions of node and dmenu are you running? What O/S?

And what locale are you using? If it's not UTF-8 I guess we have the smoking gun. (you can try to run `locate` in your terminal).

**Comment by fdietze** [comment]
I'm on Arch Linux with node 0.12.0 and dmenu 4.5.
```
❯ locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

Simple examples with dmenu are working:
```
❯ echo "ü\nä\n" | dmenu
ü
```
(I can type the characters to match the input.)

Any Idea?

**Comment by gustavnikolaj** [comment]
I have tried to reproduce it, but I cant... Both places that I read data from dmenu (via child_process spawn/exec) I read content as utf-8 - it's not set explicitly, but it is the default when no encoding is provided. 

As far as I can tell there is no difference with how it works between 0.10 and 0.12. I tested both.

Can you reproduce the problem with this code?

```javascript
require('child_process').exec('echo | dmenu -p "Prompt:"', function () {
    console.log(arguments);
});
```

I get the following output.

```
$ node test.js
{ '0': null, '1': 'üøæå\n', '2': '' }
```

**Comment by fdietze** [comment]
This is working without problems:
```
❯ node test.js
{ '0': null, '1': 'üöä\n', '2': '' }
```

**Comment by gustavnikolaj** [comment]
I must say that I don't have a clue about what is going on here. It's pretty much the same as I'm doing in the code. https://github.com/gustavnikolaj/keepass-dmenu/blob/master/lib/passwordPrompt.js#L20

I'll take a look at it when I go home. I suspect that it might be the library I use to generate the password credentials that messes up the charsets or something.

**Comment by gustavnikolaj** [comment]
I just pass what I get from child_process.exec to https://github.com/gustavnikolaj/keepass-dmenu/blob/master/lib/createPassword.js

**Comment by gustavnikolaj** [comment]
I found the problem in the library that I use to deal with the keepass files, and I filed a PR to fix the issue. I'll release a new version as soon as it is merged, or otherwise fixed. :-)

ref: https://github.com/NeoXiD/keepass.io/pull/15

**Comment by fdietze** [comment]
Well done! Thank you very much for your effort!

**Comment by gustavnikolaj** [comment]
The PR was merged yesterday, and I have updated the package and tagged a new release. :-)

**Comment by fdietze** [comment]
It's working perfectly, thank you! I really enjoy using it now.
